spring:
  application:
    name: portal-web
  resources:
    static-locations: classpath:/static
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      suffix: .html
server:
  port: 8769

eureka:
  instance:
    instance-id: portal-web
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://slave.eureka.com:8762/eureka/,http://master.eureka.com:8761/eureka/