spring:
  application:
    name: register-center
server:
  port: 8762

#配置双注册中心
eureka:
  instance:
    instance-id: register-center02
    hostname: slave.eureka.com
  client:
    serviceUrl:
      defaultZone: http://master.eureka.com:8761/eureka/