spring:
  servlet:
    multipart:
      max-file-size: 10MB # 最大支持文件大小
      max-request-size: 10MB # 最大支持请求大小
  application:
    name: shop-web
  resources:
    static-locations: classpath:/static
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      suffix: .html
server:
  port: 8768

eureka:
  instance:
    instance-id: shop-web
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://slave.eureka.com:8762/eureka/,http://master.eureka.com:8761/eureka/
