spring:
  servlet:
    multipart:
      max-file-size: 10MB # 最大支持文件大小
      max-request-size: 10MB # 最大支持请求大小
  application:
    name: file-service

# 分布式文件系统fastDfs配置
fdfs:
  # socket连接超时时长
  soTimeout: 1500
  # 连接tracker服务器超时时长
  connectTimeout: 600
  pool:
    # 从池中借出的对象的最大数目
    max-total: 153
    # 获取连接时的最大等待毫秒数100
    max-wait-millis: 102
  # 缩略图生成参数，可选
  thumbImage:
    width: 150
    height: 150
  # 跟踪服务器tracker_server请求地址,支持多个，这里只有一个，如果有多个在下方加- x.x.x.x:port
  trackerList:
    - 192.168.197.120:22122
  #
  # 存储服务器storage_server访问地址
  web-server-url: http://192.168.197.120/

server:
  port: 9000

eureka:
  instance:
    instance-id: file-service
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://slave.eureka.com:8762/eureka/,http://master.eureka.com:8761/eureka/

#文件上传基本Url
base:
  file:
    url: http://192.168.197.120/

